"""Initial migration

Revision ID: 61c6de5d6967
Revises: 
Create Date: 2025-02-01 11:12:34.003846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61c6de5d6967'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_access_log_id', table_name='access_log')
    op.drop_table('access_log')
    op.drop_index('ix_review_history_id', table_name='review_history')
    op.drop_index('ix_review_history_review_id', table_name='review_history')
    op.drop_table('review_history')
    op.drop_index('ix_category_id', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    sa.UniqueConstraint('name', name='category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    op.create_table('review_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sentiment', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='review_history_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_history_pkey')
    )
    op.create_index('ix_review_history_review_id', 'review_history', ['review_id'], unique=False)
    op.create_index('ix_review_history_id', 'review_history', ['id'], unique=False)
    op.create_table('access_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='access_log_pkey')
    )
    op.create_index('ix_access_log_id', 'access_log', ['id'], unique=False)
    # ### end Alembic commands ###
